### ISSUE TITLE
What's chinese_rip_off_winnie_the_pooh?

### ISSUE THREAD

**Issue by heipiao233** [CursedCauldron/Unvoted-Shelved#19]
[code](https://github.com/CursedCauldron/Unvoted-Shelved/blob/main-fabric-1.19/src/main/java/com/cursedcauldron/unvotedandshelved/common/entity/CopperGolemEntity.java#L392-L395)
```java
float chance = this.random.nextFloat();
if (chance < 3.4290552E-11F) {
        this.playSound(USSounds.CHINESE_RIP_OFF_WINNIE_THE_POOH, 1.0F, 1.0F);
}
```
[code](https://github.com/CursedCauldron/Unvoted-Shelved/blob/6ba927cbd9f292a7e3978f3170962f4fb9888b4c/src/main/resources/assets/unvotedandshelved/lang/en_us.json#L20)
```json
"subtitles.unvotedandshelved.chinese_rip_off_winnie_the_pooh": "Orcinus在你後面"
```
As a Chinese, I want to know what this means.

**Comment by heipiao233** [comment]
https://github.com/CursedCauldron/Unvoted-Shelved/commit/f77cfb6ca57762ef122844a76f356bed876d1e58

**Comment by heipiao233** [comment]
-

**Comment by SakuraRK** [comment]
Look likes a bullshit change.
Just for some silly political circus show.
