### ISSUE TITLE
Bug:  Copper pillar turns into copper button

### ISSUE THREAD

**Issue by juicebin** [CursedCauldron/Unvoted-Shelved#7]
When you wax a (non-oxidized) copper pillar, it turns into a (non-oxidized) copper button.

**Comment by juicebin** [comment]
Current mod-list (I have no idea how to make this a spoiler type of message, my bad for the huge paragraph):
[The Splash Milk (by marblegatekeeper)](https://www.curseforge.com/minecraft/mc-mods/the-splash-milk)
    [Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
    [Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
    [Shutup Experimental Settings! (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings)
    [Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
    [Unvoted & Shelved (by dopadreaming)](https://www.curseforge.com/minecraft/mc-mods/unvoted-shelved)
    [Flytre Lib (FlytreLib) (by Flytre7)](https://www.curseforge.com/minecraft/mc-mods/lib)
    [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
    [Smarter Farmers (farmers replant) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)
    [Mannequins (by moonflowerteam)](https://www.curseforge.com/minecraft/mc-mods/mannequins)
    [Galosphere (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/galosphere)
    [Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
    [Rare Ice (Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/rare-ice)
    [Revamped Phantoms (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/revamped-phantoms)
    [Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
    [Omnis (by theOGQueso)](https://www.curseforge.com/minecraft/mc-mods/omnis)
    [ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
    [Map Atlases [Forge] (by lilypuree)](https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge)
    [Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
    [Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
    [Potions Overhauled (by JohnSmith_474)](https://www.curseforge.com/minecraft/mc-mods/potions-overhauled)
    [TerraForged (by won_ton_)](https://www.curseforge.com/minecraft/mc-mods/terraforged)
    [Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
    [Enchanting Overhauled (by JohnSmith_474)](https://www.curseforge.com/minecraft/mc-mods/enchanting-overhauled)
    [Wall-Jump! [FORGE] (by genandnic)](https://www.curseforge.com/minecraft/mc-mods/wall-jump)
    [Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
    [Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
    [Overweight Farming (by agentmhkskg)](https://www.curseforge.com/minecraft/mc-mods/overweight-farming)
    [Easier Sleeping (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/easier-sleeping)
    [Chalk (by mortuus_art)](https://www.curseforge.com/minecraft/mc-mods/chalk)
    [Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
    [Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
    [Pollen (by moonflowerteam)](https://www.curseforge.com/minecraft/mc-mods/pollen)
    [Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
    [Compat O' Plenty (by tdstress)](https://www.curseforge.com/minecraft/mc-mods/compat-o-plenty)
    [Some Assembly Required (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/some-assembly-required)
    [Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
    [Diet (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/diet)
    [YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
    [Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
    [Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
    [Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
    [Unearthed (by lilypuree)](https://www.curseforge.com/minecraft/mc-mods/unearthed)
    [Snowy Spirit (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/snowy-spirit)
    [Sneaky Curses [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/sneaky-curses-forge)
    [Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
    [Oreganized Mod (by gleepjepomeranc)](https://www.curseforge.com/minecraft/mc-mods/oreganized-mod)
    [Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
    [TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
    [KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
    [True Darkness (by GrondagTheBarbarian)](https://www.curseforge.com/minecraft/mc-mods/true-darkness)
    [LootJS: KubeJS Addon (by Lytho_)](https://www.curseforge.com/minecraft/mc-mods/lootjs-forge)
    [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
    [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
    [YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
    [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
    [Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
    [Northern Compass (by LX_Gaming)](https://www.curseforge.com/minecraft/mc-mods/northerncompass)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [Dismal's Weapons (by 2Dismal)](https://www.curseforge.com/minecraft/mc-mods/dismals-weapons)
    [Puzzles Lib [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
    [Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
    [Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
    [Cursery[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cursery)
    [YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
    [YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
    [Lucent (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/lucent)
    [Haunted Harvest (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/haunted-harvest)
    [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [Hardcore Torches (Forge) (by WolfieWaffle)](https://www.curseforge.com/minecraft/mc-mods/hardcore-torches-forge)
    [Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
    [Cultural Delights (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights)
    [Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
    [Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [The Wild Backport (by blackgear27)](https://www.curseforge.com/minecraft/mc-mods/the-wild-backport)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [Dual Riders (by Flytre7)](https://www.curseforge.com/minecraft/mc-mods/dual-riders)
    [Not Enough Animations (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
    [YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
    [YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
    [Cold Sweat (by MikulDev)](https://www.curseforge.com/minecraft/mc-mods/cold-sweat)
    [GoProne (by Alpvax)](https://www.curseforge.com/minecraft/mc-mods/goprone)
    [Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
    [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
    [Dusk[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dusk)
    [Off Hand Combat [Forge] (by Awekyuwusu)](https://www.curseforge.com/minecraft/mc-mods/off-hand-combat)
    [Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
    [Mysterious Mountain Lib (by sz0999312)](https://www.curseforge.com/minecraft/mc-mods/mysterious-mountain-lib)
    [YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
    [KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
    [Consecration (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/consecration)
    [Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
    [Hyle (by lilypuree)](https://www.curseforge.com/minecraft/mc-mods/hyle)
    [YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
    [Disc Dissection (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/disc-dissection)
    [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
    [GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [Tumbleweed (by bconv)](https://www.curseforge.com/minecraft/mc-mods/tumbleweed)
    [Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
    [Feature NBT Deadlock Be Gone (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone)
    [Create: Alloyed (by MythrilBagels)](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)

**Comment by 0rc1nus** [comment]
Which version are you using?

**Comment by juicebin** [comment]
> Which version are you using?

Forge 2.0.1

**Comment by 0rc1nus** [comment]
Fixed in Forge 2.0.2, thanks for the bug report
