### ISSUE TITLE
Incompatible Copper Button Recipe

### ISSUE THREAD

**Issue by juicebin** [CursedCauldron/Unvoted-Shelved#8]
The recipe for the copper button is the same as the recipe that allows you to convert your copper block into copper ingots. The ladder will always replace the prior, making it impossible to craft a copper button without the use of an external mod such as Polymorph.

**Comment by 0rc1nus** [comment]
Fixed on 2.0.4 Patch 1 Forge

**Comment by juicebin** [comment]
> Fixed on 2.0.4 Patch 1 Forge

Could this be fixed for 1.18.2 as well perchance?
