### ISSUE TITLE
Unable to mine any stone type with pickaxe in V2.0.3 1.18.2

### ISSUE THREAD

**Issue by FusionSwarly** [CursedCauldron/Unvoted-Shelved#9]
I was unable to mine any stone type with a diamond pickaxe with this mod installed. Uninstalling fixed the issue. Unsure if this happens for all pickaxe types or specifically diamond, but it seems that pickaxes aren't recognized as the correct tool for mining stone.

I haven't tested any other versions. I'm running this in a small modpack, I can send the mod list if you need it.

**Comment by 0rc1nus** [comment]
Fixed in 2.0.4 - 1.18.2
